apiVersion: v1
kind: ConfigMap
metadata:
  name: streams-config
  labels:
    {{- include "demo-stream-processor.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.streamConfig }}
  {{$key }}: |-
    {{- $value | nindent 2 }}
{{- end }}

