apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-kafka-config
  labels:
    {{- include "fluentd-kafka.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.fileConfigs }}
  {{$key }}: |-
    {{- $value | nindent 4 }}
{{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-kafka-main
  labels:
    {{- include "fluentd-kafka.labels" . | nindent 4 }}
data:
  fluent.conf: |-
    # do not collect fluentd logs to avoid infinite loops.
    <label @FLUENT_LOG>
      <match **>
        @type null
        @id ignore_fluent_logs
      </match>
    </label>
    @include config.d/*.conf
    {{- range $key := .Values.configMapConfigs }}
    {{- print "@include " $key ".d/*"  | nindent 4 }}
    {{- end }}
